<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class sa1 extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable= [
        'A1_FILIAL'
        ,'A1_PESSOA'
        ,'A1_NOME'
        ,'A1_IDENT'
        ,'A1_CLIENTE'
        ,'A1_FORNEC'
        ,'A1_VEND'
        ,'A1_TPCGC'
        ,'A1_CGC'
        ,'A1_TIPO'
        ,'A1_TIPORUR'
        ,'A1_CEP'
        ,'A1_END'
        ,'A1_BAIRRO'
        ,'A1_REGIAO'
        ,'A1_MUN'
        ,'A1_EST'
        ,'A1_COD_MUN'
        ,'A1_PAIS'
        ,'A1_INSCR'
        ,'A1_INSCRM'
        ,'A1_GRPTRIB'
        ,'A1_COMISS'
        ,'A1_COMEMIS'
        ,'A1_COMBX'
        ,'A1_FONE'
        ,'A1_CELULAR'
        ,'A1_FAX'
        ,'A1_EMAIL'
        ,'A1_ENFE'
        ,'A1_HPAGE'
        ,'A1_FTP'
        ,'A1_TABELA'
        ,'A1_NREDUZ'
        ,'A1_CONTATO'
        ,'A1_RECPIS'
        ,'A1_RECCOFI'
        ,'A1_RECCSLL'
        ,'A1_OBSERV'
        ,'A1_RAMOATV'
        ,'A1_CREDITO'
        ,'A1_LIMCRED'
        ,'A1_ATIVO'
        ,'A1_VENDE1'
        ,'A1_VENDE2'
        ,'A1_VENDE3'
        ,'A1_COND'
        ,'A1_CTADEB'
        ,'A1_CTACRED'
        ,'A1_SUFRAMA'
        ,'A1_VENCIM'
        ,'A1_COMCLI'
        ,'A1_CODSIAF'
        ,'A1_TRANSP'
        ,'A1_SIMPLES'
        ,'A1_REGESIM'
        ,'A1_PERCATM'
        ,'A1_ALEMISS'
        ,'A1_ALBAIXA'
        ,'A1_TVAR1'
        ,'A1_TVAR2'
        ,'A1_TVAR3'
        ,'A1_TVAR4'
        ,'A1_CALCSUF'
        ,'A1_MENNOTA'
        ,'A1_MENPAD1'
        ,'A1_MENPAD2'
        ,'A1_MENPAD3'
        ,'A1_MENPAD4'
        ,'A1_MENPAD5'
        ,'A1_TPFRETE'
        ,'A1_CODUSER'
        ,'A1_DUPCRED'
        ,'A1_UMOVME'
        ,'A1_MSEXP'
        ,'A1_UMOVINT'
        ,'A1_UMOVID'
        ,'A1_UMOVATV'
        ,'A1_DTINCL'
        ,'D_E_L_E_T_'
        ,'R_E_C_N_O_'
        ,'A1_ETRANSP'
        ,'A1_IPDV'
        ,'A1_IPDVINT'
        ,'A1_IPDVID'
        ,'A1_IPDVATV'
        ,'A1_PFISICA'
        ,'A1_ICSHOP'
        ,'A1_ATVCSHP'
        ,'A1_DTALTCS'
        ,'A1_CSHOPID'
        ,'A1_CSHPUTC'
        ,'A1_PDVPAD'
        ,'A1_IPDVCHV'
        ,'A1_MSDT'
        ,'A1_PERFCP'
        ,'A1_CONTRIB'
        ,'A1_OUTRMUN'
        ,'A1_CODANTT'
        ,'A1_RETISS'
        ,'A1_MSAPPI'
        ,'A1_MSAPPA'
        ,'A1_MSUSRI'
        ,'A1_MSUSRA'
        ,'A1_TPNFSE'
        ,'A1_GUID'
        ,'A1_FLYID'
        ,'A1_FLYUPD'
        ,'A1_FLYDEL'

    ];
    protected $primaryKey = 'R_E_C_N_O_';
    protected $table = 'SA1';
}
