<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class se1 extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $fillable= [
        'E1_FILIAL'
        , 'E1_NUM'
        , 'E1_PARCELA'
        , 'E1_TIPO'
        , 'E1_PESSOA'
        , 'E1_NOME'
        , 'E1_SERIE'
        , 'E1_EMISSAO'
        , 'E1_CODCAT'
        , 'E1_VENCTO'
        , 'E1_VENCORI'
        , 'E1_VENCREA'
        , 'E1_VALOR'
        , 'E1_VALIRRF'
        , 'E1_BANCO'
        , 'E1_AGENCIA'
        , 'E1_CONTA'
        , 'E1_DESCRI'
        , 'E1_SALDO'
        , 'E1_MOEDA'
        , 'E1_RECIBO'
        , 'E1_NUMBOR'
        , 'E1_DATABOR'
        , 'E1_IDCNAB'
        , 'E1_SEUNUM'
        , 'E1_CNAB'
        , 'E1_NUMBCO'
        , 'E1_SITUACA'
        , 'E1_OCORREN'
        , 'E1_INSTR1'
        , 'E1_INSTR2'
        , 'E1_MARCA'
        , 'E1_ORIGEM'
        , 'E1_STATUS'
        , 'E1_DTDIGIT'
        , 'E1_DTEXP'
        , 'E1_LOCIMP'
        , 'E1_CART'
        , 'E1_ESPEC'
        , 'E1_VLRABAT'
        , 'E1_VLRIOF'
        , 'E1_INSTDES'
        , 'E1_VLRDESC'
        , 'E1_DTADESC'
        , 'E1_TPJUROS'
        , 'E1_TXJUROS'
        , 'E1_DJUROS'
        , 'E1_TXMULTA'
        , 'E1_DMULTA'
        , 'E1_BAIXA'
        , 'E1_DBAIXA'
        , 'E1_PROST'
        , 'E1_DPROST'
        , 'E1_SACADO'
        , 'E1_CGC'
        , 'E1_MSGSAC'
        , 'E1_MSGFCOM'
        , 'E1_RATEIO'
        , 'E1_FILORIG'
        , 'E1_IRPAGO'
        , 'E1_FLUXO'
        , 'E1_SEQUEN'
        , 'E1_LANPAD'
        , 'E1_VEND1'
        , 'E1_COMIS1'
        , 'E1_VEND2'
        , 'E1_COMIS2'
        , 'E1_VEND3'
        , 'E1_COMIS3'
        , 'E1_VALMERC'
        , 'E1_OBSERV'
        , 'E1_DOCCHK'
        , 'E1_IMPST'
        , 'E1_IMPIPI'
        , 'D_E_L_E_T_'
        , 'R_E_C_N_O_'
        , 'E1_CONTRA'
        , 'E1_CONDPDV'
        , 'E1_RDNUMPV'
        , 'E1_RDDTCV'
        , 'E1_RDNUMCV'
        , 'E1_RDAUT'
        , 'E1_FORMAPG'
        , 'E1_COND'
        , 'E1_TOTPARC'
        , 'E1_SUBTIT'
        , 'E1_OPERPG'
        , 'E1_BANDCA'
        , 'E1_AUTOID'
        , 'E1_PAGO'
        , 'E1_MSDT'
        , 'E1_MSAPPI'
        , 'E1_MSAPPA'
        , 'E1_MSUSRI'
        , 'E1_MSUSRA'
        , 'E1_SALCHEQ'
        , 'E1_FLYID'
        , 'E1_FLYUPD'
        , 'E1_FLYDEL'
    ];
    protected $primaryKey = 'R_E_C_N_O_';
    protected $table = 'SE1';
}
